# Використання офіційного Nginx образу як базового
FROM nginx:alpine

# Копіювання згенерованих файлів до Nginx
COPY dist /usr/share/nginx/html

# Встановлення конфігурації Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Відкриття порту
EXPOSE 3000